# Generated by Django 4.1.7 on 2023-04-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_task_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', '-created_at']},
        ),
    ]
